add new command to Charge Point to send on MQTT its OCPP config
c-jimenez/open-ocpp-simu pull request #13
Opened 2023-02-23 14:46 UTC by LucasDREZET

2023-02-27 07:49 UTC, c-jimenez requested changes
Il faudrait rajouter dans le readme le nom du topic sur lequel est envoyé la config OCPP.

2023-02-27 07:49 UTC, c-jimenez commented on README.md
> +So for there are 2 commands:
```suggestion
So far there are 2 commands:
```

2023-02-27 14:20 UTC, LucasDREZET commented
> Il faudrait rajouter dans le readme le nom du topic sur lequel est envoyé la config OCPP.

Already [here](https://github.com/c-jimenez/open-ocpp-simu/blob/dev/mqtt_send_ocpp_config/README.md?plain=1#L364)
![image](https://user-images.githubusercontent.com/33202916/221587983-62da596e-788b-4a24-8516-1820a128d4c3.png) but we can place it somewhere else if needed.

2023-02-28 07:28 UTC, c-jimenez approved these changes

2023-02-28 07:29 UTC, merged